branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pip install -r requirements.txt --use-mirrors
script:
- make html
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
  - secure: fUQw9sHISYBpiWjWd+Da+VO8TyurSSUMq7VCrEeiEwgnv+IyXPnqxW1btB39V0Qj1H2nUwEZbW/M6mrql/RqYDxj6Mg4kUPRZ1xrN6d4XhE8gD6AxREwY2+BQ4GiHk94Jy7/72J9yaT8o2TSKJQf+DdTi+5IzkNiywR/iKJvqeE=
before_install:
- git submodule update --init --recursive
after_success: ./deploy.sh
