branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pip install -r requirements.txt --use-mirrors
script:
- make html
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
  - secure: K1fov6mo8lBAif84N5v2d02lEd28lItaoWhat4d9VDYvlfnrW0NaJ1+CgLHiqEq0FtnNlJR/y9MGDtxjAl30vyysbyICPVgzeU8HJaBio6o0x/3ncv7znW2JxbiCChNAJFzDSTAm/OYosUhEHANAlDh9ikMCezlwy/WsOfKCxEI=
before_install:
- git submodule update --init --recursive
after_success: ./deploy.sh
