branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pip install -r requirements.txt --use-mirrors
script:
- make html
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
  - secure: JBIC5ygqa7pxV84j9qFj6qeYmhw5wPLzeop95cX3PxAD375QDGSZh0bsVlu9fIdPKtqJ+zlh3oFc77m8ZEt8HhkXTmF0NZnF6cgqR12e5e+/LGGcGCBKPvaloNzhcY7EPHxZxVJg2igPNRky0YkPIw27zlbDwwJMoq/AuWoDngM=
before_install:
- git submodule update --init --recursive
after_success: ./deploy.sh
