branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pip install -r requirements.txt --use-mirrors
script:
- make html
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
  - secure: mf4KWJ0g8d/JaWmjG/grMhXJuJtWJPaHKMqrLCzAwjNGgsOi14vQsvsa3lny/9i1AoCdS/DhT45vdSHe71PP6B26uZ+xV9ei8f+e9yVhsOV04F1OWZtnMscTC5z0SpAu+oqoSJlYOZcB/5JWVK6hZMjFaqil5gvC0iYmBWzxZM0=
before_install:
- git submodule update --init --recursive
after_success: ./deploy.sh
