branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pip install -r requirements.txt --use-mirrors
script:
- make html
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
  - secure: rRwKpV/WNdn2o5+DYPBVF4ujmvZlEyutAvd4oTBMvHLUWPKQPjrtQE1tzAEcpjm+5gXyN11XykxcAiaNiItIKJJ9lEVBQapc3wOYm+Hbx9QI6FRHmcbMymL2ccTA4TB/qpkjQzOrZz/bzHvkZq9mN7YX1KCbK88f7xYp4cPGdV0=
before_install:
- git submodule update --init --recursive
after_success: ./deploy.sh
